### ISSUE TITLE
Performance analysis & Baseline Profiles

### ISSUE THREAD

**Issue by miduch** [android/architecture-templates#55]
should these templates include some dummy Macrobenchmark tests & Baseline Profiles generation?

**Comment by JoseAlcerreca** [comment]
I lean towards no to keep them simple, but @keyboardsurfer @mlykotom thoughts?

**Comment by mlykotom** [comment]
I'm conflicted. 

On one hand, I'd say let's have it, because it's almost free performance improvement and it might help people who haven't heard about them.  Ideally we think everyone should generate them for their app, which is a + for having it in the template.

On the other hand, it's not architecture per se.

**Comment by keyboardsurfer** [comment]
For maintenance reasons we currently only keep baseline profile generation and macrobenchmarking in the [performance samples](github.com/android/performance-samples) and [Now in Android](github.com/android/nowinandroid) at the moment. Instead of adding them into the templates at the moment, WDYT of linking to the samples?

**Comment by miduch** [comment]
any decision on this request?

**Comment by JoseAlcerreca** [comment]
We're going to keep these templates simple by relying on the official performance samples and NiA. Thank you for the great suggestion!
